name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: yarn
      - name: Build Library
        run: yarn build:ci
      - name: Get package.json Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: packages/dist
      - name: Echo package.json version
        run: echo "${{ steps.package-version.outputs.current-version }}"
      # - name: Upload Artifact on push
      #   if: github.event_name == 'push'
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: bundle-${{ steps.package-version.outputs.current-version }}
      #     path: packages/dist
      - name: Publish to Npm
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          package: ./packages/dist/package.json
          token: ${{ secrets.NPM_TOKEN }}
          check-version: 'true'
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
