name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: yarn
      - name: Build Library
        run: yarn build:ci
      - name: Get package.json Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
        with:
          path: packages/dist
      - name: Echo package.json version
        run: echo "${{ steps.package-version.outputs.current-version }}"
      # - name: Upload Artifact on push
      #   if: github.event_name == 'push'
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: bundle-${{ steps.package-version.outputs.current-version }}
      #     path: packages/dist
      - name: Publish if version has been updated
        if: github.event_name == 'push'
        uses: pascalgn/npm-publish-action@1.3.6
        with:
          create_tag: 'true'
          workspace: 'packages/dist'
          publish_args: '--non-interactive'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
