name: Build Demo

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: yarn
      - name: Build Library
        run: yarn build:all
      - name: Build Demo
        run: yarn build:demo
      - name: Deploy demo on Netlify
        uses: netlify/actions/cli@master
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_DEMO }}
        with:
          args: deploy --dir=packages/examples/angular/dist --prod
          secrets: '["DEV_NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID_DEMO"]'
